version: '2'
services:
  ctf2_backend:
    build: ./backend
    container_name: ctf2_backend
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.ctf2_backend.rule=Host(`ctfweb.it-apostol.ru`) && PathPrefix(`/api`)"
     - "traefik.http.routers.ctf2_backend.entrypoints=http"
     - "traefik.http.services.ctf2_backend.loadbalancer.server.port=80"
  ctf2_frontend:
    build: ./front
    container_name: ctf2_frontend
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.ctf2_frontend.rule=Host(`ctfweb.it-apostol.ru`)"
     - "traefik.http.routers.ctf2_frontend.entrypoints=http"
     - "traefik.http.services.ctf2_frontend.loadbalancer.server.port=80"
    environment:
      - API_LINK=http://ctfweb.it-apostol.ru/api
      - PORT=80
  
    