version: '2'
services:
  ctf2_frontend:
    build: ./front
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.ctf2_frontend.rule=Host(`ctf2.it-apostol.ru`)"
     - "traefik.http.routers.ctf2_frontend.entrypoints=http"
     - "traefik.http.services.ctf2_frontend.loadbalancer.server.port=3000"
  ctf2_backend:
    build: ./backend
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.ctf2_frontend.rule=Host(`ctf2.it-apostol.ru`) && Path(`/api`)"
     - "traefik.http.routers.ctf2_frontend.entrypoints=http"
     - "traefik.http.services.ctf2_frontend.loadbalancer.server.port=5000"
    